### ISSUE TITLE
Best place for general discussions about this project?

### ISSUE THREAD

**Issue by filipesmedeiros** [cloudflare/wildebeest#242]
Hey! I have deployed an instance. It was actually pretty solid for something that is just starting and is "living on the edge" (pun intended).

I have a couple of concerns though (regarding, for example, account creation, domains, etc). What would be the best place for these general discussions? Should we consider opening the Discussions feature in the repo?

Thanks!

The only thing that's stopping me from adopting this as my main account is that CF doesn't support .eu domains, which honestly is pretty sad. I'd pay for this service!

**Comment by xtuc** [comment]
As long as it's not security related, please feel free to ask / comment here.

**Comment by filipesmedeiros** [comment]
Okay nice, thanks for the help!

1. My profile in the instance shows as empty. Is this intended? If I go to the timelines, the toots show, though. <img width="699" alt="Screenshot 2023-02-10 at 01 19 59" src="https://user-images.githubusercontent.com/26208850/217968757-93b8a4ce-ec09-46f3-a603-9cdcfc310c90.png">
2. Will there ever be a way to login without going through Access? If not, how would I migrate my instance to other compatible servers, one day, if I wanna change providers?
3. How well will this scale? Can we expect to not touch any configs, and it will just work? Of course the price will also go up, but I mean actually spinning up new stuff won't be necessary because it's all "serverless" right?
4. How do I control costs?
5. How do I change configs? For example if I wanna close registrations or defederate other servers, etc, how do I do it, given that it seems Pinaforce doesn't have those options? I'm sorry, I'm a bit of a noob so this might be a dumb question
6. Sometimes I get "Internet request failed. Showing offline data" on Pinaforce. I assume something is failing, but will be fixed?
7. The speed at which my Mastodon account shows toots I made in this instance is relatively slow. Don't know it that's normal for Mastodon servers/AP servers in general, or if the "default" deploy on CF is just slow for some reason?

I think that's it for now ahah Sorry if it's too much at once. Just want to remind that if this all goes smoothly, I will be a paying customer, and gladly, because I wanna self-host, and haven't done it for fear of wasting time on sys-admin stuff!

**Comment by MischaBoender** [comment]
> The only thing that's stopping me from adopting this as my main account is that CF doesn't support .eu domains... 

Not sure what support you are referring to, but I've been running my .eu off CF for years (DNS and Workers). I don't use CF as a registrar.

**Comment by filipesmedeiros** [comment]
@MischaBoender I'm so dumb! Of course! I will be doing that. Do you happen to know it's safe to just move the nameservers? I have a bunch of important stuff running on that domain, it won't ruin that right? Ahah

**Comment by MischaBoender** [comment]
Never had any issue with changing nameservers. When you onboard a domain in CF it will first try to figure out what existing DNS records you have and also let's you pre-set all required DNS records. Then if you change nameservers the DNS zone is ready on CF side.

**Comment by xtuc** [comment]
@filipesmedeiros, thanks for your feedback / questions.

> 1. My profile in the instance shows as empty. Is this intended?

Yes, showing toots on profiles isn't implemented yet.

> 2. Will there ever be a way to login without going through Access? If not, how would I migrate my instance to other compatible servers, one day, if I wanna change providers?

We only allow Cloudflare Access, but all auth provider should be supported. Could you please tell me more about the relation to instance migration?

> 3. How well will this scale?

The project is fairly new so can't give a definitive anwser, but https://cloudflare.social is using it. I can see issues with the D1 database size limit of 100Mb, but the team is working to increase.

> 4. How do I control costs?

I don't really know to be honest, I know for Cloudflare Images you pay for a maximum number of images so cost have a ceiling. Might be the same for Workers?

> 5. How do I change configs? For example if I wanna close registrations or defederate other servers

There's not many configuration available to you, just because the project is fairly new. That said, registration are closed by default because they are handled by Cloudflare Access. As long as you give someone access via Cloudflare Access, they will be allowed to register.

> 6. Sometimes I get "Internet request failed. Showing offline data" on Pinaforce

Could you please check in the developer console, network tab, which calls are failing exactly? It could be unimplemented endpoints or bugs which we can fix.

> 7. The speed at which my Mastodon account shows toots I made in this instance is relatively slow

For publishing a toot to followers we use a queue, the queue is configured with a 30sec buffer (delay in practice) to batch messages. I believe that's the delay your are seeing. Does it cause any issues? It's meant to reduce the queue consumer invokation and thus cost.

**Comment by bretcarmichael** [comment]
1. Are any moderation tools available, like deleting posts in the event you receive a DMCA takedown request?
2. Is there a way to show an /about page with policies and admin contact information?
3. Can I block instances? I think this is a higher priority given there's some pretty unsavory stuff out there that I don't want near me or anyone I allow on my server.

The reason I'm asking is, in the US, it's in our interest to register a registered agent with the copyright office in case someone posts to our servers. It helps with S230 protections and is generally protective.

**Comment by xtuc** [comment]
> 1. Are any moderation tools available, like deleting posts in the event you receive a DMCA takedown request?

There's no moderation tools yet. A workaround is deleting posts manually from the database.

> 2. Is there a way to show an /about page with policies and admin contact information?
> 3. Can I block instances?
> 4. Is it possible for a user to filter timeline to a language(s)?

These features aren't implemented yet. Please feel free to create dedicated issues for us to implement them.

**Comment by xtuc** [comment]
@filipesmedeiros I'm closing this issue, please feel free to reach out if you have any other questions / concerns.
